version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_DB: fin_advisor
    volumes:
      - db_data:/var/lib/postgresql/data # persists data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5431:5432" # optional: expose to host

  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3001"

volumes:
  db_data:
